name: Feature Request
description: Request a new feature or enhancement
title: "[Feature]: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Claude will pick this up and start working on it.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What feature would you like to see?
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would you use this feature? Provide an example.
      placeholder: |
        ```al
        // Example of how you'd like to use this feature
        Mutate.Customer('10000')
            .Set(Name, 'New Name')
            .Apply();
        ```
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: How do we know when this is done?
      placeholder: |
        - [ ] Feature works as described
        - [ ] Tests are included
        - [ ] Documentation is updated

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Low - Nice to have
        - Medium - Would be useful
        - High - Really need this
    validations:
      required: true
